SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_Modes](
	[id_Mode] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Mode] [varchar](50) NOT NULL
) ON [PRIMARY]

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_Modes](
	[id_Mode] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Mode] [varchar](50) NOT NULL
) ON [PRIMARY]

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_Modes](
	[id_Mode] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Mode] [varchar](50) NOT NULL
) ON [PRIMARY]

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_Modes](
	[id_Mode] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Mode] [varchar](50) NOT NULL
) ON [PRIMARY]

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_Modes](
	[id_Mode] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Mode] [varchar](50) NOT NULL
) ON [PRIMARY]

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_Modes](
	[id_Mode] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Mode] [varchar](50) NOT NULL
) ON [PRIMARY]

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_Modes](
	[id_Mode] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Mode] [varchar](50) NOT NULL
) ON [PRIMARY]

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_Modes](
	[id_Mode] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Mode] [varchar](50) NOT NULL
) ON [PRIMARY]

